#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial clean functions
. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"

# Delete the following:
# - time directories
# - constant/polyMesh directory
# - postProcessing and VTK directories
# - log files
# - field files with a ".orig" backup
rm -r postProcessing
rm -r log.*
rm -r processor*
foamListTimes -rm
rm -r *.OpenFOAM
rm -r *.blockMesh
# rm -r meltingData
rm -r cellRemovalData
#------------------------------------------------------------------------------
