#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#任意方法执行得到cellProc场
runApplication decomposePar -allRegions -cellProc
#修改cellProc，添加边界才能setFields
runApplication setFields -region gas -time 13.9
runApplication setFields -region solid -time 13.9

#将cellProc修改为cellDecomposition文件
#修改decomposeDict为manual
runApplication decomposePar -allRegions -force

#------------------------------------------------------------------------------
